"""
All Pydantic output schemas used by Oracle's LLM calls.

Every LLM call in the codebase uses instructor with one of these schemas.
No free-form string parsing anywhere.
"""

from __future__ import annotations

from pydantic import BaseModel


class FunctionSummary(BaseModel):
    """LLM-generated summary of a long function (>= SUMMARIZE_MIN_LINES)."""
    summary: str  # 5-10 sentences covering: what it does, params with types,
                  # return value and type, exceptions, algorithms, deps, side effects.


class QueryClassification(BaseModel):
    """Layer-3 LLM routing output."""
    level: str          # "directory" | "file" | "class" | "function" | "all"
    confidence: float   # 0.0–1.0
    reasoning: str      # one sentence


class ChunkCitation(BaseModel):
    """A single cited chunk reference in a Q&A answer."""
    chunk_id: str
    file_path: str
    line_range: str         # "lines 45–78"
    relevance: str          # one sentence explaining why this chunk is relevant


class QAAnswer(BaseModel):
    """Structured answer returned by the Q&A engine."""
    answer: str             # Direct answer, 1–3 paragraphs
    confidence: float       # 0.0–1.0
    cited_chunks: list[ChunkCitation]
    follow_up_suggestions: list[str]   # 2–3 related questions


class CodePatch(BaseModel):
    """Search-and-replace patch generated by the resolver."""
    file_path: str
    original_code: str      # Must be exact verbatim substring of the current file
    new_code: str
    explanation: str
    confidence: float
    affects_other_files: list[str]


class TestResult(BaseModel):
    """Output of running the test suite."""
    passed: bool
    framework: str          # "pytest" | "jest" | "unknown"
    total_tests: int | None
    failed_tests: list[str]
    output_summary: str     # First 500 chars of stdout + stderr
    timed_out: bool


class PRResult(BaseModel):
    """Result of PR creation (or dry-run preview)."""
    dry_run: bool
    pr_url: str | None      # None when dry_run=True
    pr_title: str           # "[Auto] Fix: {issue_title}"
    pr_body: str            # Full markdown preview
    branch_name: str        # "oracle/fix-issue-{issue_number}"


class IssueAnalysis(BaseModel):
    """Analysis of a GitHub issue against the indexed codebase."""
    relevant_files: list[str]
    relevant_chunks: list[ChunkCitation]
    identified_identifiers: list[str]
    suggested_fix_scope: str    # "single_function" | "multiple_files" | "unknown"
